<?php
/**
 * Default template for events index
 *
 * Do not edit this file, place a copy into your template path
 * with the same name and it will be used instead. This is to
 * allow updates to not overwrite your custom templates
 *
 * @author James Collings <james@jclabs.co.uk>
 * @package WP Engine / Events
 */

get_header(); ?>

<?php do_action('before_theme_content'); ?>

<h1>No Access</h1>
<p>To view this content please <a href="<?php echo wp_login_url($_SERVER["REQUEST_URI"]); ?>">login</a> or <a href="<?php echo site_url('/register'); ?>">register an account</a> with the website.</p>

<?php do_action('after_theme_content'); ?>

<?php get_footer(); ?>